services:
  agent:
    image: grafana/agent:v0.31.3
    environment:
      - GRAFANA_USERNAME
      - GRAFANA_API_KEY
    command:
      - "--config.file.type=dynamic"
      - "--enable-features=dynamic-config,integrations-next"
      - "--config.file"
      - "file:///etc/grafana-agent/agent.yml"
    volumes:
      - "./grafana-agent:/etc/grafana-agent"
  caddy:
    image: caddy:2.6.4
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://agent:4317"
      OTEL_SERVICE_NAME: "caddy"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "8080:8080"
  frontend:
    build: .
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://agent:4317"
      OTEL_SERVICE_NAME: "frontend"
    volumes:
      - "./bin/demo:/usr/local/bin/demo"
    command:
      - /usr/local/bin/demo
      - frontend
  backend:
    build: .
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://agent:4317"
      OTEL_SERVICE_NAME: "backend"
    volumes:
      - "./bin/demo:/usr/local/bin/demo"
    command:
      - /usr/local/bin/demo
      - backend
